name: Node.js Application Start Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-start:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Ensure npm 11.0.0
      run: |
        npm install -g npm@11.0.0
        npm --version
    
    - name: Install dependencies
      run: npm install
    
    - name: Build (if needed)
      run: npm run build --if-present
    
    - name: Test npm start
      run: |
        npm start &
        APP_PID=$!
        
        sleep 10
        
        if ps -p $APP_PID > /dev/null; then
          echo "✅ L'application a démarré avec succès"
          kill $APP_PID
          exit 0
        else
          echo "❌ L'application n'a pas réussi à démarrer correctement"
          exit 1
        fi
